/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Assess delta spec sync state**

   Resolve the **changes path** first. Read \`openspec/config.yaml\` for the \`changesDir\` setting; if present, use that path. Otherwise default to \`openspec/changes/\`. The change's delta specs live at \`<changesDir>/<name>/specs/\`. When status JSON provides \`artifactPaths.specs.existingOutputPaths\`, use it to determine which delta specs exist. If no \`specs/\` directory exists (and \`existingOutputPaths\` is empty), skip the sync step (no delta to sync) and proceed without a sync prompt.

   **If delta specs exist:**
   - For each \`<changesDir>/<name>/specs/<capability>/spec.md\`:
     - Check whether the corresponding main spec exists at \`openspec/specs/<capability>/spec.md\` (project-local, what the openspec CLI reads — distinct from \`changesDir\`)
     - If both exist: diff to determine what changes would be applied (adds, modifications, removals, renames)
     - If only delta exists: this is a NEW capability; the sync will be a create
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   **If user chooses sync, perform the delta→main transformation inline** (the legacy \`openspec-sync-specs\` skill is not installed in most setups; do the work directly):

   For each capability in the change's \`specs/\`:

   a. **Read the delta spec** at \`<changesDir>/<name>/specs/<capability>/spec.md\`. The delta uses headers like \`## ADDED Requirements\`, \`## MODIFIED Requirements\`, \`## REMOVED Requirements\`.

   b. **Determine the target shape** based on whether \`openspec/specs/<capability>/spec.md\` already exists:

      - **NEW capability (no existing main spec)**: synthesise the main spec from the delta by:
        - Replacing the title line with \`# <capability> Specification\`
        - Inserting a frontmatter block at the top with \`type: capability\`, the source \`module\` (carried over from the delta frontmatter when present), and a \`sources:\` list whose only entry is \`<change-name> (archived <YYYY-MM-DD>)\`
        - Inserting a \`## Purpose\` section after the title — a 1-2 paragraph plain-language summary derived from the proposal's \`## Why\` (if available) or from the delta requirement texts
        - Collapsing \`## ADDED Requirements\` and \`## MODIFIED Requirements\` (treat both as flat for a fresh spec) into a single \`## Requirements\` section
        - Dropping \`## REMOVED Requirements\` entirely (nothing to remove from a non-existent main spec)
        - Keeping every \`### Requirement: ...\` block and \`#### Scenario: ...\` block intact

      - **EXISTING capability (main spec already exists)**: merge inline
        - For each \`### Requirement:\` under \`## ADDED Requirements\` → append to the main spec's \`## Requirements\` section
        - For each \`### Requirement:\` under \`## MODIFIED Requirements\` → locate the matching requirement in the main spec by title and overwrite its body + scenarios
        - For each \`### Requirement:\` under \`## REMOVED Requirements\` → delete that requirement block from the main spec
        - Preserve the main spec's existing frontmatter, \`## Purpose\`, and any sections other than \`## Requirements\`
        - Append the change name to the \`sources:\` list in frontmatter (create the list if missing)

   c. **Write the result** to \`openspec/specs/<capability>/spec.md\` (creating the directory if needed). This is the project-local path the openspec CLI reads.

   d. **Validate**: run \`openspec validate --specs\` and confirm the capability shows up with \`requirements N\` > 0 and no parse errors. If validation fails, surface the diff to the user and ask whether to roll back or proceed.

   e. **Stage for commit (advisory)**: report the file paths so the user can include them in their next commit; do NOT commit on the user's behalf.

   (Project overlays may mirror the synthesised spec to a long-term spec store such as an Obsidian vault — see schema-/plugin-level overlay docs.)

   Proceed to archive regardless of whether sync succeeded or was skipped. Sync failures are recorded as warnings; the archive itself still completes (the user can re-run sync later).

5. **Check for schema-level archive definition**

   From the status JSON, check the \`schemaName\`. Read the schema's YAML to see if it defines an \`archive\` phase with steps.

   **If the schema defines archive steps** (e.g., \`archive.steps\` in schema.yaml):
   - Before the standard mv archive, execute each schema-defined step in order
   - For each step: show progress, execute according to \`method\` (gate/free), report result
   - Plugin hooks (\`archive.pre\`/\`archive.post\`) will fire automatically if defined
   - After all steps complete, proceed to the standard mv archive below

   **If no schema archive definition exists:**
   - Proceed directly to the standard mv archive below

6. **Perform the archive**

   Create an \`archive\` directory under \`planningHome.changesDir\` if it doesn't exist:
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move \`changeRoot\` to the archive directory

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Whether specs were synced (if applicable)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs (or "No delta specs" or "Sync skipped")

All artifacts complete. All tasks complete.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, perform delta→main transformation inline per step 4 (the legacy \`openspec-sync-specs\` skill is not installed in most setups)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- If schema defines archive hooks, run \`openspec run start --phase archive --json\` to trigger them`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/opsx:archive\` (e.g., \`/opsx:archive add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Prompt user for confirmation to continue
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Assess delta spec sync state**

   Resolve the **changes path** first. Read \`openspec/config.yaml\` for the \`changesDir\` setting; if present, use that path. Otherwise default to \`openspec/changes/\`. The change's delta specs live at \`<changesDir>/<name>/specs/\`. When status JSON provides \`artifactPaths.specs.existingOutputPaths\`, use it to determine which delta specs exist. If no \`specs/\` directory exists (and \`existingOutputPaths\` is empty), skip the sync step (no delta to sync) and proceed without a sync prompt.

   **If delta specs exist:**
   - For each \`<changesDir>/<name>/specs/<capability>/spec.md\`:
     - Check whether the corresponding main spec exists at \`openspec/specs/<capability>/spec.md\` (project-local, what the openspec CLI reads — distinct from \`changesDir\`)
     - If both exist: diff to determine what changes would be applied (adds, modifications, removals, renames)
     - If only delta exists: this is a NEW capability; the sync will be a create
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   **If user chooses sync, perform the delta→main transformation inline** (the legacy \`openspec-sync-specs\` skill is not installed in most setups; do the work directly):

   For each capability in the change's \`specs/\`:

   a. **Read the delta spec** at \`<changesDir>/<name>/specs/<capability>/spec.md\`. The delta uses headers like \`## ADDED Requirements\`, \`## MODIFIED Requirements\`, \`## REMOVED Requirements\`.

   b. **Determine the target shape** based on whether \`openspec/specs/<capability>/spec.md\` already exists:

      - **NEW capability (no existing main spec)**: synthesise the main spec from the delta by:
        - Replacing the title line with \`# <capability> Specification\`
        - Inserting a frontmatter block at the top with \`type: capability\`, the source \`module\` (carried over from the delta frontmatter when present), and a \`sources:\` list whose only entry is \`<change-name> (archived <YYYY-MM-DD>)\`
        - Inserting a \`## Purpose\` section after the title — a 1-2 paragraph plain-language summary derived from the proposal's \`## Why\` (if available) or from the delta requirement texts
        - Collapsing \`## ADDED Requirements\` and \`## MODIFIED Requirements\` (treat both as flat for a fresh spec) into a single \`## Requirements\` section
        - Dropping \`## REMOVED Requirements\` entirely (nothing to remove from a non-existent main spec)
        - Keeping every \`### Requirement: ...\` block and \`#### Scenario: ...\` block intact

      - **EXISTING capability (main spec already exists)**: merge inline
        - For each \`### Requirement:\` under \`## ADDED Requirements\` → append to the main spec's \`## Requirements\` section
        - For each \`### Requirement:\` under \`## MODIFIED Requirements\` → locate the matching requirement in the main spec by title and overwrite its body + scenarios
        - For each \`### Requirement:\` under \`## REMOVED Requirements\` → delete that requirement block from the main spec
        - Preserve the main spec's existing frontmatter, \`## Purpose\`, and any sections other than \`## Requirements\`
        - Append the change name to the \`sources:\` list in frontmatter (create the list if missing)

   c. **Write the result** to \`openspec/specs/<capability>/spec.md\` (creating the directory if needed). This is the project-local path the openspec CLI reads.

   d. **Validate**: run \`openspec validate --specs\` and confirm the capability shows up with \`requirements N\` > 0 and no parse errors. If validation fails, surface the diff to the user and ask whether to roll back or proceed.

   e. **Stage for commit (advisory)**: report the file paths so the user can include them in their next commit; do NOT commit on the user's behalf.

   (Project overlays may mirror the synthesised spec to a long-term spec store such as an Obsidian vault — see schema-/plugin-level overlay docs.)

   Proceed to archive regardless of whether sync succeeded or was skipped. Sync failures are recorded as warnings; the archive itself still completes (the user can re-run sync later).

5. **Check for schema-level archive definition**

   From the status JSON, check the \`schemaName\`. Read the schema's YAML to see if it defines an \`archive\` phase with steps.

   **If the schema defines archive steps** (e.g., \`archive.steps\` in schema.yaml):
   - Before the standard mv archive, execute each schema-defined step in order
   - For each step: show progress, execute according to \`method\` (gate/free), report result
   - Plugin hooks (\`archive.pre\`/\`archive.post\`) will fire automatically if defined
   - After all steps complete, proceed to the standard mv archive below

   **If no schema archive definition exists:**
   - Proceed directly to the standard mv archive below

6. **Perform the archive**

   Create an \`archive\` directory under \`planningHome.changesDir\` if it doesn't exist:
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move \`changeRoot\` to the archive directory

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Spec sync status (synced / sync skipped / no delta specs)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (No Delta Specs)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** No delta specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success With Warnings**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** Sync skipped (user chose to skip)

**Warnings:**
- Archived with 2 incomplete artifacts
- Archived with 3 incomplete tasks
- Delta spec sync was skipped (user chose to skip)

Review the archive if this was not intentional.
\`\`\`

**Output On Error (Archive Exists)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Target:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/

Target archive directory already exists.

**Options:**
1. Rename the existing archive
2. Delete the existing archive if it's a duplicate
3. Wait until a different date to archive
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, perform delta→main transformation inline per step 4 (the legacy \`openspec-sync-specs\` skill is not installed in most setups)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- If schema defines archive hooks, run \`openspec run start --phase archive --json\` to trigger them`
  };
}
